<a href="https://colab.research.google.com/github/asma-mo/Estate-Elite-Insights/blob/ran_branch/KPIs/python_code/Rental_Yield.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Rental Yield

##import data

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd /content/drive/MyDrive/Prello/clean data/

/content/drive/MyDrive/Prello/clean data

In [3]:
%ls

 clean_notary_real_estate_sales.csv  'real_estate_info_by_municipality (2).csv'

###notary_real_estate_sales

In [4]:
import pandas as pd
copied_path = "/content/drive/MyDrive/Prello/clean data/clean_notary_real_estate_sales.csv"
df_sales = pd.read_csv(copied_path)

In [5]:
df_sales.head()

,sales_date,sales_amount,street_number,street_code,street_name,city_name,municipality_code,premise_type,surface,number_of_principal_rooms,sales_price_m2,latitude,longitude
0,2018-02-06,5000000.0,63.0,0040,AV PRINCE RAINIER III,Saint-Jean-Cap-Ferrat,06121,Maison,292,10,17123,43.678892,7.330651
1,2018-11-26,93060.0,5308.0,B061,LE SERRET,Vallées-d'Antraigues-Asperjoc,07011,Maison,16,0,5816,44.714072,4.360185
2,2018-06-08,95000.0,161.0,0683,IMP COL EMILE VIGUIER,Millau,12145,Maison,21,0,4524,44.093714,3.054594
3,2018-07-17,3912000.0,690.0,1868,CHE DE MAZARGUES,Aix-en-Provence,13001,Maison,610,13,6413,43.502833,5.428194
4,2018-03-27,810000.0,5000.0,0162,CHE DES OLIVIERS,Eygalières,13034,Maison,296,9,2736,43.756881,4.957214

In [6]:
df_sales.dtypes

sales_date                    object
sales_amount                 float64
street_number                float64
street_code                   object
street_name                   object
city_name                     object
municipality_code             object
premise_type                  object
surface                        int64
number_of_principal_rooms      int64
sales_price_m2                 int64
latitude                     float64
longitude                    float64
dtype: object

In [7]:
df_sales["sales_date"] = pd.to_datetime(df_sales["sales_date"])

In [8]:
df_sales.dtypes

sales_date                   datetime64[ns]
sales_amount                        float64
street_number                       float64
street_code                          object
street_name                          object
city_name                            object
municipality_code                    object
premise_type                         object
surface                               int64
number_of_principal_rooms             int64
sales_price_m2                        int64
latitude                            float64
longitude                           float64
dtype: object

In [9]:
df_sales.head()

,sales_date,sales_amount,street_number,street_code,street_name,city_name,municipality_code,premise_type,surface,number_of_principal_rooms,sales_price_m2,latitude,longitude
0,2018-02-06,5000000.0,63.0,0040,AV PRINCE RAINIER III,Saint-Jean-Cap-Ferrat,06121,Maison,292,10,17123,43.678892,7.330651
1,2018-11-26,93060.0,5308.0,B061,LE SERRET,Vallées-d'Antraigues-Asperjoc,07011,Maison,16,0,5816,44.714072,4.360185
2,2018-06-08,95000.0,161.0,0683,IMP COL EMILE VIGUIER,Millau,12145,Maison,21,0,4524,44.093714,3.054594
3,2018-07-17,3912000.0,690.0,1868,CHE DE MAZARGUES,Aix-en-Provence,13001,Maison,610,13,6413,43.502833,5.428194
4,2018-03-27,810000.0,5000.0,0162,CHE DES OLIVIERS,Eygalières,13034,Maison,296,9,2736,43.756881,4.957214

###real_estate_info_by_municipality

In [10]:
%ls

 clean_notary_real_estate_sales.csv  'real_estate_info_by_municipality (2).csv'

In [11]:
copied_path = "/content/drive/MyDrive/Prello/clean data/real_estate_info_by_municipality (2).csv"
df_restate = pd.read_csv(copied_path)

In [12]:
df_restate.head()

,municipality_code,demand_level,rental_max_apartment,rental_min_apartment,rental_med_house,rental_max_house,rental_min_house,rental_med_all,rental_max_all,rental_min_all
0,57133,8,12.27,9.07,9.19,14.45,6.64,9.53,13.77,7.25
1,57446,8,18.22,7.69,10.92,14.16,7.77,11.09,15.97,7.73
2,77013,9,18.30,8.39,12.20,16.71,9.21,12.26,16.75,9.19
3,77026,9,15.76,6.28,9.51,13.20,7.04,9.53,13.23,7.03
4,77072,9,17.50,7.69,11.47,15.75,8.21,11.47,15.75,8.21

In [13]:
df_restate.dtypes

municipality_code        object
demand_level              int64
rental_max_apartment    float64
rental_min_apartment    float64
rental_med_house        float64
rental_max_house        float64
rental_min_house        float64
rental_med_all          float64
rental_max_all          float64
rental_min_all          float64
dtype: object

##calculating the KPI

###premises type

In [14]:
pd.value_counts(df_sales.premise_type)

Maison         2177488
Appartement    1644241
Name: premise_type, dtype: int64

####maison = home

In [15]:
mask_df_sales_Maison = df_sales["premise_type"] == "Maison"
mask_df_sales_Maison

0           True
1           True
2           True
3           True
4           True
           ...
3821724    False
3821725    False
3821726    False
3821727    False
3821728    False
Name: premise_type, Length: 3821729, dtype: bool

In [16]:
df_sales_Maison = df_sales[mask_df_sales_Maison]
df_sales_Maison.head()

,sales_date,sales_amount,street_number,street_code,street_name,city_name,municipality_code,premise_type,surface,number_of_principal_rooms,sales_price_m2,latitude,longitude
0,2018-02-06,5000000.0,63.0,0040,AV PRINCE RAINIER III,Saint-Jean-Cap-Ferrat,06121,Maison,292,10,17123,43.678892,7.330651
1,2018-11-26,93060.0,5308.0,B061,LE SERRET,Vallées-d'Antraigues-Asperjoc,07011,Maison,16,0,5816,44.714072,4.360185
2,2018-06-08,95000.0,161.0,0683,IMP COL EMILE VIGUIER,Millau,12145,Maison,21,0,4524,44.093714,3.054594
3,2018-07-17,3912000.0,690.0,1868,CHE DE MAZARGUES,Aix-en-Provence,13001,Maison,610,13,6413,43.502833,5.428194
4,2018-03-27,810000.0,5000.0,0162,CHE DES OLIVIERS,Eygalières,13034,Maison,296,9,2736,43.756881,4.957214

In [17]:
pd.value_counts(df_sales_Maison.premise_type)

Maison    2177488
Name: premise_type, dtype: int64

####Appartement = apartment

In [18]:
mask_df_sales_Appartement = df_sales["premise_type"] == "Appartement"
mask_df_sales_Appartement

0          False
1          False
2          False
3          False
4          False
           ...
3821724     True
3821725     True
3821726     True
3821727     True
3821728     True
Name: premise_type, Length: 3821729, dtype: bool

In [19]:
df_sales_Appartement = df_sales[mask_df_sales_Appartement]
df_sales_Appartement.head()

,sales_date,sales_amount,street_number,street_code,street_name,city_name,municipality_code,premise_type,surface,number_of_principal_rooms,sales_price_m2,latitude,longitude
111988,2018-09-21,285000.0,9003.0,B037,BEAUVAIS,Nogent-le-Rotrou,28280,Appartement,227,12,1256,48.305165,0.810056
111989,2020-03-16,60000.0,5656.0,B016,AURON,Saint-Étienne-de-Tinée,06120,Appartement,15,0,4000,44.225695,6.930653
111990,2018-09-12,94000.0,81.0,4652,AV JEAN RIEUX,Toulouse,31555,Appartement,14,0,6714,43.595862,1.463813
111991,2018-10-20,4800.0,142.0,B038,KOZ KASTELL,Plouguerneau,29195,Appartement,6,0,800,48.593167,-4.452340
111992,2018-12-21,550000.0,42.0,1780,RUE GAMBETTA,Arras,62041,Appartement,310,9,1774,NaN,NaN

In [34]:
pd.value_counts(df_sales_Appartement.premise_type)

Appartement    1644241
Name: premise_type, dtype: int64

####real estate info house

In [68]:
df_restate_Maison = df_restate[["municipality_code","rental_max_house","rental_min_house","rental_med_all"]]
df_restate_Maison

      municipality_code  rental_max_house  rental_min_house  rental_med_all
0                 57133             14.45              6.64            9.53
1                 57446             14.16              7.77           11.09
2                 77013             16.71              9.21           12.26
3                 77026             13.20              7.04            9.53
4                 77072             15.75              8.21           11.47
...                 ...               ...               ...             ...
34436             81126             11.28              6.45            8.93
34437             33425             14.72              7.40           11.09
34438             85146             13.50              8.43           10.88
34439             53062             11.28              6.15            8.69
34440             22093             13.81              6.51            9.80

[34441 rows x 4 columns]

In [ ]:
df_restate_Maison.rename(columns = {'rental_max_house':'rental_max'}, inplace = True)

In [ ]:
df_restate_Maison.rename(columns = {'rental_min_house':'rental_min'}, inplace = True)

In [ ]:
df_restate_Maison.rename(columns = {'rental_med_all':'rental_med'}, inplace = True)

In [80]:
df_restate_Maison

      municipality_code  rental_max  rental_min  rental_med
0                 57133       14.45        6.64        9.53
1                 57446       14.16        7.77       11.09
2                 77013       16.71        9.21       12.26
3                 77026       13.20        7.04        9.53
4                 77072       15.75        8.21       11.47
...                 ...         ...         ...         ...
34436             81126       11.28        6.45        8.93
34437             33425       14.72        7.40       11.09
34438             85146       13.50        8.43       10.88
34439             53062       11.28        6.15        8.69
34440             22093       13.81        6.51        9.80

[34441 rows x 4 columns]

####real estate info apartment

In [71]:
df_restate_Appartement = df_restate[["municipality_code","rental_max_apartment","rental_min_apartment","rental_med_all"]]
df_restate_Appartement

,municipality_code,rental_max_apartment,rental_min_apartment,rental_med_all
0,57133,12.27,9.07,9.53
1,57446,18.22,7.69,11.09
2,77013,18.30,8.39,12.26
3,77026,15.76,6.28,9.53
4,77072,17.50,7.69,11.47
...,...,...,...,...
34436,81126,16.64,6.36,8.93
34437,33425,16.20,7.90,11.09
34438,85146,18.51,8.22,10.88
34439,53062,16.12,6.28,8.69
34440,22093,14.25,6.58,9.80

In [ ]:
df_restate_Appartement.rename(columns = {'rental_max_apartment':'rental_max'}, inplace = True)

In [ ]:
df_restate_Appartement.rename(columns = {'rental_min_apartment':'rental_min'}, inplace = True)

In [ ]:
df_restate_Appartement.rename(columns = {'rental_med_all':'rental_med'}, inplace = True)

In [84]:
df_restate_Appartement

      municipality_code  rental_max  rental_min  rental_med
0                 57133       12.27        9.07        9.53
1                 57446       18.22        7.69       11.09
2                 77013       18.30        8.39       12.26
3                 77026       15.76        6.28        9.53
4                 77072       17.50        7.69       11.47
...                 ...         ...         ...         ...
34436             81126       16.64        6.36        8.93
34437             33425       16.20        7.90       11.09
34438             85146       18.51        8.22       10.88
34439             53062       16.12        6.28        8.69
34440             22093       14.25        6.58        9.80

[34441 rows x 4 columns]

###joining tables

####house

In [51]:
df_sales_Maison.head(1)

,sales_date,sales_amount,street_number,street_code,street_name,city_name,municipality_code,premise_type,surface,number_of_principal_rooms,sales_price_m2,latitude,longitude
0,2018-02-06,5000000.0,63.0,0040,AV PRINCE RAINIER III,Saint-Jean-Cap-Ferrat,06121,Maison,292,10,17123,43.678892,7.330651

In [52]:
df_sales_Maison.shape

(2177488, 13)

In [85]:
df_restate_Maison.head(1)

  municipality_code  rental_max  rental_min  rental_med
0             57133       14.45        6.64        9.53

In [86]:
df_restate_Maison.shape

(34441, 4)

In [100]:
rental_yield_maison = pd.merge(df_sales_Maison, df_restate_Maison, on="municipality_code", how="left")
rental_yield_maison.head(1)

,sales_date,sales_amount,street_number,street_code,street_name,city_name,municipality_code,premise_type,surface,number_of_principal_rooms,sales_price_m2,latitude,longitude,rental_max,rental_min,rental_med
0,2018-02-06,5000000.0,63.0,0040,AV PRINCE RAINIER III,Saint-Jean-Cap-Ferrat,06121,Maison,292,10,17123,43.678892,7.330651,26.71,14.19,17.29

In [88]:
rental_yield_maison.shape

(2177488, 16)

####apartment

In [89]:
df_sales_Appartement.head(1)

,sales_date,sales_amount,street_number,street_code,street_name,city_name,municipality_code,premise_type,surface,number_of_principal_rooms,sales_price_m2,latitude,longitude
111988,2018-09-21,285000.0,9003.0,B037,BEAUVAIS,Nogent-le-Rotrou,28280,Appartement,227,12,1256,48.305165,0.810056

In [90]:
df_sales_Appartement.shape

(1644241, 13)

In [91]:
df_restate_Appartement.head(1)

  municipality_code  rental_max  rental_min  rental_med
0             57133       12.27        9.07        9.53

In [92]:
df_restate_Appartement.shape

(34441, 4)

In [93]:
rental_yield_Appartement = pd.merge(df_sales_Appartement, df_restate_Appartement, on="municipality_code", how="left")
rental_yield_Appartement.head(1)

,sales_date,sales_amount,street_number,street_code,street_name,city_name,municipality_code,premise_type,surface,number_of_principal_rooms,sales_price_m2,latitude,longitude,rental_max,rental_min,rental_med
0,2018-09-21,285000.0,9003.0,B037,BEAUVAIS,Nogent-le-Rotrou,28280,Appartement,227,12,1256,48.305165,0.810056,16.32,6.68,9.38

In [94]:
rental_yield_Appartement.shape

(1644241, 16)

###Concatenate Tables

In [105]:
rental_yield_maison.shape

(2177488, 16)

In [96]:
rental_yield_Appartement.shape

(1644241, 16)

the output should be 3821729 rows

In [107]:
rental_yield = pd.concat([rental_yield_maison,rental_yield_Appartement], axis = 0)
rental_yield

,sales_date,sales_amount,street_number,street_code,street_name,city_name,municipality_code,premise_type,surface,number_of_principal_rooms,sales_price_m2,latitude,longitude,rental_max,rental_min,rental_med
0,2018-02-06,5000000.0,63.0,0040,AV PRINCE RAINIER III,Saint-Jean-Cap-Ferrat,06121,Maison,292,10,17123,43.678892,7.330651,26.71,14.19,17.29
1,2018-11-26,93060.0,5308.0,B061,LE SERRET,Vallées-d'Antraigues-Asperjoc,07011,Maison,16,0,5816,44.714072,4.360185,NaN,NaN,NaN
2,2018-06-08,95000.0,161.0,0683,IMP COL EMILE VIGUIER,Millau,12145,Maison,21,0,4524,44.093714,3.054594,14.96,7.22,10.15
3,2018-07-17,3912000.0,690.0,1868,CHE DE MAZARGUES,Aix-en-Provence,13001,Maison,610,13,6413,43.502833,5.428194,22.11,9.77,16.49
4,2018-03-27,810000.0,5000.0,0162,CHE DES OLIVIERS,Eygalières,13034,Maison,296,9,2736,43.756881,4.957214,17.98,9.57,13.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1644236,2017-11-10,160000.0,9001.0,A055,RES LA COUPIANE,La Valette-du-Var,83144,Appartement,103,5,1553,43.127825,5.988491,22.45,9.90,14.75
1644237,2019-03-15,290000.0,9001.0,A278,RES LES TROIS MAGES,Aix-en-Provence,13001,Appartement,103,6,2816,43.516165,5.470374,27.85,10.50,16.49
1644238,2018-04-26,540000.0,9001.0,A370,RES LE GAUGUIN CHEM BRUNET,Aix-en-Provence,13001,Appartement,115,5,4696,43.538090,5.438490,27.85,10.50,16.49
1644239,2021-08-25,184000.0,9001.0,0002,BD ABEL LEFEVRE,Ézy-sur-Eure,27230,Appartement,150,3,1227,48.862603,1.422561,20.52,8.36,11.82
1644240,2021-08-31,610000.0,9001.0,A155,RES DES ILES LE MONTE CRISTO,Ajaccio,2A004,Appartement,150,5,4067,41.910640,8.710564,22.38,10.07,13.99

In [98]:
rental_yield.shape

(3821729, 16)

###measuring rental_yield KPI

In [110]:
rental_yield.dtypes

sales_date                   datetime64[ns]
sales_amount                        float64
street_number                       float64
street_code                          object
street_name                          object
city_name                            object
municipality_code                    object
premise_type                         object
surface                               int64
number_of_principal_rooms             int64
sales_price_m2                        int64
latitude                            float64
longitude                           float64
rental_max                          float64
rental_min                          float64
rental_med                          float64
dtype: object

In [111]:
rental_yield["rental_yield_max"] = rental_yield["surface"] * rental_yield["rental_max"]
rental_yield

,sales_date,sales_amount,street_number,street_code,street_name,city_name,municipality_code,premise_type,surface,number_of_principal_rooms,sales_price_m2,latitude,longitude,rental_max,rental_min,rental_med,rental_yield_max
0,2018-02-06,5000000.0,63.0,0040,AV PRINCE RAINIER III,Saint-Jean-Cap-Ferrat,06121,Maison,292,10,17123,43.678892,7.330651,26.71,14.19,17.29,7799.32
1,2018-11-26,93060.0,5308.0,B061,LE SERRET,Vallées-d'Antraigues-Asperjoc,07011,Maison,16,0,5816,44.714072,4.360185,NaN,NaN,NaN,NaN
2,2018-06-08,95000.0,161.0,0683,IMP COL EMILE VIGUIER,Millau,12145,Maison,21,0,4524,44.093714,3.054594,14.96,7.22,10.15,314.16
3,2018-07-17,3912000.0,690.0,1868,CHE DE MAZARGUES,Aix-en-Provence,13001,Maison,610,13,6413,43.502833,5.428194,22.11,9.77,16.49,13487.10
4,2018-03-27,810000.0,5000.0,0162,CHE DES OLIVIERS,Eygalières,13034,Maison,296,9,2736,43.756881,4.957214,17.98,9.57,13.55,5322.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1644236,2017-11-10,160000.0,9001.0,A055,RES LA COUPIANE,La Valette-du-Var,83144,Appartement,103,5,1553,43.127825,5.988491,22.45,9.90,14.75,2312.35
1644237,2019-03-15,290000.0,9001.0,A278,RES LES TROIS MAGES,Aix-en-Provence,13001,Appartement,103,6,2816,43.516165,5.470374,27.85,10.50,16.49,2868.55
1644238,2018-04-26,540000.0,9001.0,A370,RES LE GAUGUIN CHEM BRUNET,Aix-en-Provence,13001,Appartement,115,5,4696,43.538090,5.438490,27.85,10.50,16.49,3202.75
1644239,2021-08-25,184000.0,9001.0,0002,BD ABEL LEFEVRE,Ézy-sur-Eure,27230,Appartement,150,3,1227,48.862603,1.422561,20.52,8.36,11.82,3078.00
1644240,2021-08-31,610000.0,9001.0,A155,RES DES ILES LE MONTE CRISTO,Ajaccio,2A004,Appartement,150,5,4067,41.910640,8.710564,22.38,10.07,13.99,3357.00

In [112]:
rental_yield["rental_yield_min"] = rental_yield["surface"] * rental_yield["rental_min"]
rental_yield["rental_yield_med"] = rental_yield["surface"] * rental_yield["rental_med"]
rental_yield

,sales_date,sales_amount,street_number,street_code,street_name,city_name,municipality_code,premise_type,surface,number_of_principal_rooms,sales_price_m2,latitude,longitude,rental_max,rental_min,rental_med,rental_yield_max,rental_yield_min,rental_yield_med
0,2018-02-06,5000000.0,63.0,0040,AV PRINCE RAINIER III,Saint-Jean-Cap-Ferrat,06121,Maison,292,10,17123,43.678892,7.330651,26.71,14.19,17.29,7799.32,4143.48,5048.68
1,2018-11-26,93060.0,5308.0,B061,LE SERRET,Vallées-d'Antraigues-Asperjoc,07011,Maison,16,0,5816,44.714072,4.360185,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-06-08,95000.0,161.0,0683,IMP COL EMILE VIGUIER,Millau,12145,Maison,21,0,4524,44.093714,3.054594,14.96,7.22,10.15,314.16,151.62,213.15
3,2018-07-17,3912000.0,690.0,1868,CHE DE MAZARGUES,Aix-en-Provence,13001,Maison,610,13,6413,43.502833,5.428194,22.11,9.77,16.49,13487.10,5959.70,10058.90
4,2018-03-27,810000.0,5000.0,0162,CHE DES OLIVIERS,Eygalières,13034,Maison,296,9,2736,43.756881,4.957214,17.98,9.57,13.55,5322.08,2832.72,4010.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1644236,2017-11-10,160000.0,9001.0,A055,RES LA COUPIANE,La Valette-du-Var,83144,Appartement,103,5,1553,43.127825,5.988491,22.45,9.90,14.75,2312.35,1019.70,1519.25
1644237,2019-03-15,290000.0,9001.0,A278,RES LES TROIS MAGES,Aix-en-Provence,13001,Appartement,103,6,2816,43.516165,5.470374,27.85,10.50,16.49,2868.55,1081.50,1698.47
1644238,2018-04-26,540000.0,9001.0,A370,RES LE GAUGUIN CHEM BRUNET,Aix-en-Provence,13001,Appartement,115,5,4696,43.538090,5.438490,27.85,10.50,16.49,3202.75,1207.50,1896.35
1644239,2021-08-25,184000.0,9001.0,0002,BD ABEL LEFEVRE,Ézy-sur-Eure,27230,Appartement,150,3,1227,48.862603,1.422561,20.52,8.36,11.82,3078.00,1254.00,1773.00
1644240,2021-08-31,610000.0,9001.0,A155,RES DES ILES LE MONTE CRISTO,Ajaccio,2A004,Appartement,150,5,4067,41.910640,8.710564,22.38,10.07,13.99,3357.00,1510.50,2098.50

##cleaning data

In [113]:
rental_yield.isnull().sum()

sales_date                       0
sales_amount                     0
street_number                22830
street_code                      0
street_name                     52
city_name                        0
municipality_code                0
premise_type                     0
surface                          0
number_of_principal_rooms        0
sales_price_m2                   0
latitude                     49502
longitude                    49502
rental_max                   91389
rental_min                   91389
rental_med                   91389
rental_yield_max             91389
rental_yield_min             91389
rental_yield_med             91389
dtype: int64