<a href="https://colab.research.google.com/github/asma-mo/Estate-Elite-Insights/blob/rahaf_branch/data_cleaning/python_code/housing_stock.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import auth
import pandas as pd
auth.authenticate_user()
project_id="data-analytics-bootcamp-363212"
data="prello"
table="housing_stock"
query =  f"SELECT * FROM `{project_id}.{data}.{table}`"
housing_stock=pd.read_gbq(query, project_id)
housing_stock

,int64_field_0,municipality_code,year,nb_principal_home,nb_second_home,nb_vacants_housing,nb_tot_housing,secondary_home_rate,principal_home_rate,vacants_housing_rate,country_code
0,25,01339,1968,109,155,0,264,0.587121,0.412879,0.000000,1
1,89,02368,1968,132,56,0,188,0.297872,0.702128,0.000000,1
2,203,04073,1968,134,93,0,227,0.409692,0.590308,0.000000,1
3,238,04148,1968,42,93,0,135,0.688889,0.311111,0.000000,1
4,270,05012,1968,70,53,0,123,0.430894,0.569106,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...
279579,275947,13105,2018,2951,48,202,3201,0.014995,0.921899,0.063105,1
279580,276174,78380,2018,2325,48,205,2578,0.018619,0.901862,0.079519,1
279581,276753,95352,2018,1918,48,212,2178,0.022039,0.880624,0.097337,1
279582,277014,59279,2018,8137,48,471,8656,0.005545,0.940042,0.054413,1
279583,278356,63231,2018,782,48,235,1065,0.045070,0.734272,0.220657,1

drop int64_field_0	column

In [ ]:
# Display the original DataFrame
print("Original DataFrame:")
print(housing_stock)

# Drop a column by specifying the column name
column_name = 'int64_field_0'
housing_stock = housing_stock.drop(column_name, axis=1)

# Display the modified DataFrame
print("Modified DataFrame:")
print(housing_stock)

Original DataFrame:
        int64_field_0 municipality_code  year  nb_principal_home  \
0                  25             01339  1968                109
1                  89             02368  1968                132
2                 203             04073  1968                134
3                 238             04148  1968                 42
4                 270             05012  1968                 70
...               ...               ...   ...                ...
279579         275947             13105  2018               2951
279580         276174             78380  2018               2325
279581         276753             95352  2018               1918
279582         277014             59279  2018               8137
279583         278356             63231  2018                782

        nb_second_home  nb_vacants_housing  nb_tot_housing  \
0                  155                   0             264
1                   56                   0             188
2                   93                   0             227
3                   93                   0             135
4                   53                   0             123
...                ...                 ...             ...
279579              48                 202            3201
279580              48                 205            2578
279581              48                 212            2178
279582              48                 471            8656
279583              48                 235            1065

        secondary_home_rate  principal_home_rate  vacants_housing_rate  \
0                  0.587121             0.412879              0.000000
1                  0.297872             0.702128              0.000000
2                  0.409692             0.590308              0.000000
3                  0.688889             0.311111              0.000000
4                  0.430894             0.569106              0.000000
...                     ...                  ...                   ...
279579             0.014995             0.921899              0.063105
279580             0.018619             0.901862              0.079519
279581             0.022039             0.880624              0.097337
279582             0.005545             0.940042              0.054413
279583             0.045070             0.734272              0.220657

        country_code
0                  1
1                  1
2                  1
3                  1
4                  1
...              ...
279579             1
279580             1
279581             1
279582             1
279583             1

[279584 rows x 11 columns]
Modified DataFrame:
       municipality_code  year  nb_principal_home  nb_second_home  \
0                  01339  1968                109             155
1                  02368  1968                132              56
2                  04073  1968                134              93
3                  04148  1968                 42              93
4                  05012  1968                 70              53
...                  ...   ...                ...             ...
279579             13105  2018               2951              48
279580             78380  2018               2325              48
279581             95352  2018               1918              48
279582             59279  2018               8137              48
279583             63231  2018                782              48

        nb_vacants_housing  nb_tot_housing  secondary_home_rate  \
0                        0             264             0.587121
1                        0             188             0.297872
2                        0             227             0.409692
3                        0             135             0.688889
4                        0             123             0.430894
...                    ...             ...                  ...
279579                 202            3201             0.014995
279580                 205            2578             0.018619
279581                 212            2178             0.022039
279582                 471            8656             0.005545
279583                 235            1065             0.045070

        principal_home_rate  vacants_housing_rate  country_code
0                  0.412879              0.000000             1
1                  0.702128              0.000000             1
2                  0.590308              0.000000             1
3                  0.311111              0.000000             1
4                  0.569106              0.000000             1
...                     ...                   ...           ...
279579             0.921899              0.063105             1
279580             0.901862              0.079519             1
279581             0.880624              0.097337             1
279582             0.940042              0.054413             1
279583             0.734272              0.220657             1

[279584 rows x 10 columns]

drop country_code

In [ ]:
# Display the original DataFrame
print("Original DataFrame:")
print(housing_stock)

# Drop a column by specifying the column name
column_name = 'country_code'
housing_stock = housing_stock.drop(column_name, axis=1)

# Display the modified DataFrame
print("Modified DataFrame:")
print(housing_stock)

Original DataFrame:
       municipality_code  year  nb_principal_home  nb_second_home  \
0                  01339  1968                109             155
1                  02368  1968                132              56
2                  04073  1968                134              93
3                  04148  1968                 42              93
4                  05012  1968                 70              53
...                  ...   ...                ...             ...
279579             13105  2018               2951              48
279580             78380  2018               2325              48
279581             95352  2018               1918              48
279582             59279  2018               8137              48
279583             63231  2018                782              48

        nb_vacants_housing  nb_tot_housing  secondary_home_rate  \
0                        0             264             0.587121
1                        0             188             0.297872
2                        0             227             0.409692
3                        0             135             0.688889
4                        0             123             0.430894
...                    ...             ...                  ...
279579                 202            3201             0.014995
279580                 205            2578             0.018619
279581                 212            2178             0.022039
279582                 471            8656             0.005545
279583                 235            1065             0.045070

        principal_home_rate  vacants_housing_rate  country_code
0                  0.412879              0.000000             1
1                  0.702128              0.000000             1
2                  0.590308              0.000000             1
3                  0.311111              0.000000             1
4                  0.569106              0.000000             1
...                     ...                   ...           ...
279579             0.921899              0.063105             1
279580             0.901862              0.079519             1
279581             0.880624              0.097337             1
279582             0.940042              0.054413             1
279583             0.734272              0.220657             1

[279584 rows x 10 columns]
Modified DataFrame:
       municipality_code  year  nb_principal_home  nb_second_home  \
0                  01339  1968                109             155
1                  02368  1968                132              56
2                  04073  1968                134              93
3                  04148  1968                 42              93
4                  05012  1968                 70              53
...                  ...   ...                ...             ...
279579             13105  2018               2951              48
279580             78380  2018               2325              48
279581             95352  2018               1918              48
279582             59279  2018               8137              48
279583             63231  2018                782              48

        nb_vacants_housing  nb_tot_housing  secondary_home_rate  \
0                        0             264             0.587121
1                        0             188             0.297872
2                        0             227             0.409692
3                        0             135             0.688889
4                        0             123             0.430894
...                    ...             ...                  ...
279579                 202            3201             0.014995
279580                 205            2578             0.018619
279581                 212            2178             0.022039
279582                 471            8656             0.005545
279583                 235            1065             0.045070

        principal_home_rate  vacants_housing_rate
0                  0.412879              0.000000
1                  0.702128              0.000000
2                  0.590308              0.000000
3                  0.311111              0.000000
4                  0.569106              0.000000
...                     ...                   ...
279579             0.921899              0.063105
279580             0.901862              0.079519
279581             0.880624              0.097337
279582             0.940042              0.054413
279583             0.734272              0.220657

[279584 rows x 9 columns]

disply the table

In [ ]:
housing_stock

,municipality_code,year,nb_principal_home,nb_second_home,nb_vacants_housing,nb_tot_housing,secondary_home_rate,principal_home_rate,vacants_housing_rate
0,01339,1968,109,155,0,264,0.587121,0.412879,0.000000
1,02368,1968,132,56,0,188,0.297872,0.702128,0.000000
2,04073,1968,134,93,0,227,0.409692,0.590308,0.000000
3,04148,1968,42,93,0,135,0.688889,0.311111,0.000000
4,05012,1968,70,53,0,123,0.430894,0.569106,0.000000
...,...,...,...,...,...,...,...,...,...
279579,13105,2018,2951,48,202,3201,0.014995,0.921899,0.063105
279580,78380,2018,2325,48,205,2578,0.018619,0.901862,0.079519
279581,95352,2018,1918,48,212,2178,0.022039,0.880624,0.097337
279582,59279,2018,8137,48,471,8656,0.005545,0.940042,0.054413
279583,63231,2018,782,48,235,1065,0.045070,0.734272,0.220657

In [10]:
import pandas as pd
df=pd.DataFrame(housing_stock)

In [11]:
missing_values = df.isnull().sum()
print(missing_values)

municipality_code       0
year                    0
nb_principal_home       0
nb_second_home          0
nb_vacants_housing      0
nb_tot_housing          0
secondary_home_rate     0
principal_home_rate     0
vacants_housing_rate    0
dtype: int64

In [12]:
# Check for duplicated rows
duplicated_rows = df[df.duplicated()]

# Display the duplicated rows, if any
print("Duplicated rows:")
print(duplicated_rows)

Duplicated rows:
Empty DataFrame
Columns: [municipality_code, year, nb_principal_home, nb_second_home, nb_vacants_housing, nb_tot_housing, secondary_home_rate, principal_home_rate, vacants_housing_rate]
Index: []

In [13]:
# Get the number of unique values in each column
unique_values_per_column = df.nunique()
print("Number of unique values in each column:")
print(unique_values_per_column)

Number of unique values in each column:
municipality_code       34948
year                        8
nb_principal_home        9029
nb_second_home           2854
nb_vacants_housing       2292
nb_tot_housing           9853
secondary_home_rate     66696
principal_home_rate     73070
vacants_housing_rate    51599
dtype: int64